<a href="https://colab.research.google.com/github/Prem7539/PDS-Assignments/blob/main/DL_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("/content/insurance_data1.csv")
df.head()

age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordability']], df.bought_insurance, test_size = 0.2, random_state = 25)

In [5]:
len(X_train)

21

In [6]:
df.shape

(27, 3)

In [7]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [8]:
X_test_scaled

age  affordability
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              0
14  0.49              1
9   0.61              0

In [11]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation = 'sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 949ms/step - accuracy: 0.5238 - loss: 0.7697
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5238 - loss: 0.7693
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5238 - loss: 0.7689
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5238 - loss: 0.7685
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5238 - loss: 0.7681
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5238 - loss: 0.7678
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5238 - loss: 0.7674
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5238 - loss: 0.7670
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5238 - loss: 0.7666
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5238 - loss: 0.7662
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5238 - loss: 0.7658
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5238 - loss: 0.7655


In [10]:
df

age  affordability  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              0                 1
6    55              1                 0
7    60              0                 1
8    62              1                 1
9    61              0                 1
10   18              1                 0
11   28              0                 0
12   27              1                 0
13   29              1                 0
14   49              1                 1
15   55              1                 1
16   25              1                 1
17   58              0                 1
18   19              0                 0
19   18              0                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              0                 1
24   50              1                 1
25   54              0                 1
26   23              1                 0

In [12]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step - accuracy: 0.8333 - loss: 0.5917


[0.5917329788208008, 0.8333333134651184]

In [13]:
X_test_scaled

age  affordability
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              0
14  0.49              1
9   0.61              0

In [14]:
model.predict(X_test_scaled) #predicted values

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


array([[0.67254823],
       [0.5962929 ],
       [0.47617114],
       [0.48184538],
       [0.67753583],
       [0.57505715]], dtype=float32)

In [15]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [17]:
coef, intercept = model.get_weights()
coef, intercept                          # it tells wi, w2, bias

(array([[1.1368641 ],
        [0.57637924]], dtype=float32),
 array([-0.39097235], dtype=float32))

In [41]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
sigmoid(0)

0.5

In [42]:
def prediction_function(age, affordability):
  weighted_sum = coef[0]*age + coef[1]*affordability + intercept
  return sigmoid(weighted_sum)


In [43]:
prediction_function(0.47,1)

/tmp/ipython-input-2643926644.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.6725482190943439

In [44]:
prediction_function(.18,1)

/tmp/ipython-input-2643926644.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.5962929191922575

In [45]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [46]:
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [56]:

def gradient_descent(age, affordability, y_true, epochs, loss_threshold):
  #w1, w2, bias
  w1 = w2 = 1
  bias = 0
  rate = 0.5
  n = len(age)
  for i in range(epochs):
    weighted_sum = w1 * age +w2 * affordability + bias
    y_predicted = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true, y_predicted)

    w1d = (1/n)*np.dot(np.transpose(age),(y_predicted - y_true)) # derivative of w1
    w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted - y_true)) # derivative of w2

    bias_d = np.mean(y_predicted - y_true)

    w1 = w1 - rate * w1d
    w2 = w2 - rate * w2d
    bias = bias - rate * bias_d

    print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
    if loss <= loss_threshold:
      break
  return w1, w2, bias

In [57]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordability'], y_train, 1000, 0.6630)

Epoch:0, w1:0.9866572164673553, w2:0.9148979879993606, bias:-0.09574936157785763, loss:0.7696945758092107
Epoch:1, w1:0.9788712653875846, w2:0.8387970354872757, bias:-0.17728740953876163, loss:0.738688008271839
Epoch:2, w1:0.9761387357797816, w2:0.7712224900199287, bias:-0.24587268669732673, loss:0.7154124198016338
Epoch:3, w1:0.9778768686301885, w2:0.7114643009968714, bias:-0.30296859401028947, loss:0.6981742087508536
Epoch:4, w1:0.9834796895295455, w2:0.6586872573250656, bias:-0.3500996789125155, loss:0.6854793684622829
Epoch:5, w1:0.9923605827001971, w2:0.612022997434651, bias:-0.38874278484496744, loss:0.6761039867723849
Epoch:6, w1:1.0039793181259826, w2:0.5706344663687077, bias:-0.4202581250433664, loss:0.6691000774767232
Epoch:7, w1:1.0178557192204758, w2:0.5337540262197773, bias:-0.44585455407172997, loss:0.6637635793628884
Epoch:8, w1:1.0335737017922506, w2:0.5007012160741467, bias:-0.4665793911296563, loss:0.6595875952776


(np.float64(1.0335737017922506),
 np.float64(0.5007012160741467),
 np.float64(-0.4665793911296563))

In [58]:
coef, intercept

(array([[1.1368641 ],
        [0.57637924]], dtype=float32),
 array([-0.39097235], dtype=float32))